version: '3'

services:

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: sun
    ports: [5432:5432]
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  php:
    image: sunfinance/local
    build:
      context: ./docker/php
      args:
        USER_ID: 1001
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/php/config.ini:/usr/local/etc/php/conf.d/config.ini
    depends_on:
      - database
      - rabbitmq
    networks:
      - app-network

  php-cli:
    image: sunfinance-concole/local
    build:
      context: ./docker/php-cli
      args:
        USER_ID: 1001
    volumes:
      - .:/var/www
      - ./docker/php/config.ini:/usr/local/etc/php/conf.d/config.ini
    networks:
      - app-network
    command: php bin/console messenger:consume async -vv --time-limit=3600
    depends_on:
      - rabbitmq
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 8080:15672
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    networks:
      - app-network

volumes:
  db_data: {}

networks:
  app-network:
    driver: bridge